# Generated by Django 5.2.17 on 2026-09-17 18:21

import django.db.models.deletion
import opaque_keys.edx.django.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('sequence', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('institution', models.CharField(blank=True, db_index=True, max_length=64)),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(blank=True, max_length=255, null=True)),
                ('identity_sub', models.CharField(blank=True, db_index=True, max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('occurred', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivered', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='IdentityAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_sub', models.CharField(blank=True, db_index=True, max_length=128)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('event', models.CharField(choices=[('linked', 'Existing account linked to control-plane identity'), ('created', 'Account created for control-plane identity'), ('link_refused', 'Account link refused'), ('login_refused', 'Sign-in refused (identity not active)'), ('admission_applied', 'Pending admission applied at first login'), ('roles_synced', 'Roles synchronised'), ('suspended', 'Account suspended'), ('reactivated', 'Account reactivated'), ('support_lookup', 'OEC support looked up a learner'), ('invited', 'Staff invitation sent'), ('invite_revoked', 'Staff invitation withdrawn'), ('invite_accepted', 'Staff invitation accepted'), ('partner_requested', 'Institution partnership requested'), ('partner_approved', 'Institution partnership approved'), ('partner_declined', 'Institution partnership declined')], max_length=32)),
                ('detail', models.TextField(blank=True)),
                ('actor', models.CharField(blank=True, help_text="service user or 'sso'", max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('institution', models.CharField(db_index=True, help_text='Open edX org short name', max_length=64)),
                ('role', models.CharField(choices=[('institution_admin', 'Institution administrator'), ('programme_admin', 'Programme administrator'), ('course_author', 'Course author'), ('trainer', 'Trainer'), ('instructor', 'Instructor'), ('teaching_assistant', 'Teaching assistant')], max_length=32)),
                ('course_id', models.CharField(blank=True, help_text='Course run for instructor / TA roles', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_sub', models.CharField(blank=True, db_index=True, help_text='control-plane user id (OIDC sub); NULL if unknown', max_length=128, null=True)),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('application_id', models.CharField(help_text='control-plane application identifier', max_length=64)),
                ('institution', models.CharField(help_text='institution code / Open edX org short name', max_length=64)),
                ('status', models.CharField(choices=[('submitted', 'Application submitted'), ('under_review', 'Under review'), ('admitted', 'Admitted'), ('declined', 'Not admitted'), ('withdrawn', 'Withdrawn'), ('deferred', 'Deferred')], default='admitted', max_length=16)),
                ('mode', models.CharField(default='honor', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_admissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('identity_sub', 'course_key'), ('user', 'course_key')},
            },
        ),
        migrations.CreateModel(
            name='ManagedRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=64)),
                ('org', models.CharField(blank=True, max_length=64)),
                ('course_id', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(default='token', max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role', 'org', 'course_id')},
            },
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('welcome', 'Welcome'), ('enrolment', 'Enrolment confirmed'), ('certificate', 'Credential recorded'), ('receipt', 'Payment receipt')], max_length=16)),
                ('reference', models.CharField(blank=True, help_text='course run key or certificate id; empty for account mail', max_length=255)),
                ('sent', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'kind', 'reference')},
            },
        ),
        migrations.CreateModel(
            name='SupportScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=64)),
                ('course_id', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(default='token', max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_support_scopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'institution', 'course_id')},
            },
        ),
    ]
