#!/usr/bin/env bash
# Apply public config and (re)launch the platform. Run as the `tutor` user.
# Secrets are generated by Tutor on first run and persisted in ~/.local/share/tutor/config.yml.
set -euo pipefail
cd "$(dirname "$0")/.."
python3 - <<'PY'
import subprocess, yaml
cfg = yaml.safe_load(open("config.public.yml"))
args = [f"{k}={yaml.safe_dump(v, default_flow_style=True).strip()}" for k, v in cfg.items() if k not in ("ID","PLUGINS","PLUGIN_INDEXES")]
subprocess.run(["tutor", "config", "save", *sum((["--set", a] for a in args), [])], check=True)
PY
tutor local launch -I
