#!/usr/bin/env bash
# Apply public config and (re)launch the platform. Run as the `tutor` user from a checkout of this repo.
# Secrets are generated by Tutor on first run and persisted in ~/.local/share/tutor/config.yml.
#
# The EduLage Django plugin (platform-plugin-edulage/) is bind-mounted into the openedx image
# (tutor mounts), so a Python-only change needs `tutor local restart lms cms lms-worker cms-worker`
# rather than a rebuild; a new dependency or migration needs this full script.
set -euo pipefail
cd "$(dirname "$0")/.."
mkdir -p "$(tutor plugins printroot)"
cp plugins/*.yml "$(tutor plugins printroot)/"
tutor plugins enable indigo edulage
rsync -a --delete --exclude __pycache__ platform-plugin-edulage/ "$HOME/platform-plugin-edulage/"
tutor mounts add "$HOME/platform-plugin-edulage" 2>/dev/null || true
python3 - <<'PY'
import subprocess, yaml
cfg = yaml.safe_load(open("config.public.yml"))
args = [f"{k}={yaml.safe_dump(v, default_flow_style=True).strip()}" for k, v in cfg.items() if k not in ("ID","PLUGINS","PLUGIN_INDEXES")]
subprocess.run(["tutor", "config", "save", *sum((["--set", a] for a in args), [])], check=True)
PY
tutor images build openedx
tutor local launch -I
