# Generated by Django 5.2.13 on 2026-09-07 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edulage_platform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='admission',
            unique_together={('user', 'course_key')},
        ),
        migrations.AddField(
            model_name='admission',
            name='edulage_sub',
            field=models.CharField(blank=True, db_index=True, help_text='EduLage user id (OIDC sub); NULL if unknown', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='mode',
            field=models.CharField(default='honor', max_length=32),
        ),
        migrations.AddField(
            model_name='managedrole',
            name='source',
            field=models.CharField(default='token', max_length=8),
        ),
        migrations.AlterField(
            model_name='admission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edulage_admissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='admission',
            unique_together={('edulage_sub', 'course_key'), ('user', 'course_key')},
        ),
        migrations.CreateModel(
            name='IdentityAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edulage_sub', models.CharField(blank=True, db_index=True, max_length=128)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('event', models.CharField(choices=[('linked', 'Existing account linked to EduLage identity'), ('created', 'Account created for EduLage identity'), ('link_refused', 'Account link refused'), ('admission_applied', 'Pending admission applied at first login'), ('roles_synced', 'Roles synchronised'), ('suspended', 'Account suspended'), ('reactivated', 'Account reactivated'), ('support_lookup', 'OEC support looked up a learner')], max_length=32)),
                ('detail', models.TextField(blank=True)),
                ('actor', models.CharField(blank=True, help_text="service user or 'sso'", max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SupportScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=64)),
                ('course_id', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(default='token', max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edulage_support_scopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'institution', 'course_id')},
            },
        ),
    ]
