# Generated by Django 5.2.17 on 2026-09-17 18:21

import django.db.models.deletion
import opaque_keys.edx.django.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus_platform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(max_length=255, unique=True)),
                ('institution', models.CharField(help_text='institution code / Open edX org short name', max_length=64)),
                ('institution_name', models.CharField(max_length=160)),
                ('enrolment_policy', models.CharField(choices=[('admission', 'Admission required'), ('open_free', 'Open enrolment — free'), ('open_paid', 'Open enrolment — paid')], default='admission', help_text="Set by the institution's course admin in Studio (Advanced settings → Other course settings → marketplace)", max_length=16)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Fixed price for open_paid runs', max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('institution_logo', models.URLField(blank=True)),
                ('institution_url', models.URLField(blank=True, help_text='Institution profile on the marketplace site')),
                ('programme_title', models.CharField(blank=True, help_text='Parent programme, if the run is part of one', max_length=200)),
                ('programme_url', models.URLField(blank=True, help_text='Programme page on the marketplace site')),
                ('classification', models.CharField(choices=[('degree', 'Degree programme'), ('postgraduate', 'Postgraduate programme'), ('professional', 'Professional programme'), ('certificate', 'Certificate course'), ('short', 'Short course'), ('executive', 'Executive education'), ('open', 'Open course'), ('cpd', 'Continuing professional development')], default='short', max_length=16)),
                ('credential', models.CharField(blank=True, help_text='e.g. MSc, PGD, Certificate of completion', max_length=64)),
                ('delivery_mode', models.CharField(blank=True, help_text='e.g. Fully online, Online + OEC exams', max_length=32)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=160)),
                ('short_name', models.CharField(blank=True, help_text='Proposed institution code (Open edX org short name)', max_length=16)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('website', models.URLField(blank=True)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(db_index=True, max_length=254)),
                ('contact_role', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('declined', 'Declined')], db_index=True, default='pending', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('decided', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, help_text='Reason sent to the contact on decline; internal note on approval')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campus_platform.staffinvitation')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('institution', models.CharField(db_index=True, help_text='Open edX org short name of the run', max_length=64)),
                ('reference', models.CharField(help_text='Our reference, passed to Paystack', max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Major units (e.g. NGN), price at checkout', max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('initialized', 'Initialised'), ('success', 'Successful'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], db_index=True, default='initialized', max_length=16)),
                ('email', models.EmailField(help_text='Customer e-mail sent to Paystack', max_length=254)),
                ('paystack_id', models.CharField(blank=True, help_text='Paystack transaction id', max_length=32)),
                ('channel', models.CharField(blank=True, max_length=32)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('gateway_response', models.CharField(blank=True, max_length=255)),
                ('enrolled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campus_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
